import React, { useState, useEffect } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import type { Message, ResponseOption } from '@/types/chatbot';
import { chatbotApi } from '@/lib/api-client';
import { LoadingState } from './LoadingState';
import { ConversationHistory } from './ConversationHistory';
import { ResponseOptions } from './ResponseOptions';

/**
 * Main dialog component managing chatbot state and orchestrating child components.
 * 
 * This component now integrates with the real AI chatbot API endpoint (/api/chatbot)
 * using DeepSeek to generate intelligent, context-aware responses for skill explanations.
 * 
 * Props:
 * - skillId: Unique identifier for the skill
 * - skillTitle: Display name of the skill
 * - open: Controls dialog visibility
 * - onOpenChange: Callback when dialog open state changes
 * 
 * Features:
 * - Initial AI explanation when skill dialog opens
 * - Follow-up questions generated by AI based on context
 * - Conversation history maintained for context-aware responses
 * - Conversation caching per skill in localStorage for persistence
 * - Loading states during AI response generation
 * - Typewriter animation for AI messages
 * - Mobile-optimized responsive design
 * 
 * Validates Requirements:
 * - 1.1: Dialog opens when skill container is clicked
 * - 1.2: Dialog displays in centered modal overlay
 * - 1.3: Dialog prevents interaction with background content
 * - 1.4: Loading state displays immediately on dialog open
 * - 2.1: Loading state displays animation
 * - 2.3: Loading state simulates delay between 800ms-1500ms
 * - 2.4: Loading state transitions to chatbot interface
 * - 3.1: Initial AI response loaded from API
 * - 5.3: Response option selection adds message to history
 * - 5.4: Response option selection triggers loading state
 * - 9.1: Dialog displays close button
 * - 9.2: Dialog closes with smooth animation
 * - 10.3: Smooth transition from loading state to chatbot interface (200ms fade)
 */
export interface SkillChatbotDialogProps {
  skillId: string;
  skillTitle: string;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

/**
 * Interface for cached conversation data
 */
interface CachedConversation {
  messages: Message[];
  conversationHistory: Array<{
    role: 'user' | 'assistant';
    content: string;
  }>;
  currentOptions: ResponseOption[];
  timestamp: number;
}

/**
 * Cache duration in milliseconds (24 hours)
 * Conversations older than this will be cleared
 */
const CACHE_DURATION = 24 * 60 * 60 * 1000;

/**
 * Helper function to generate unique message IDs
 */
const generateMessageId = (): string => {
  return `msg_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
};

/**
 * Helper function to convert API options to ResponseOption format
 */
const convertToResponseOptions = (options: string[]): ResponseOption[] => {
  return options.map((text, index) => ({
    id: `opt_${Date.now()}_${index}`,
    text,
    nextNodeId: null, // Will be determined when option is selected
  }));
};

/**
 * Get cached conversation from localStorage
 * 
 * @param skillId - Skill identifier for the conversation
 * @returns Cached conversation data or null if not found or expired
 */
const getCachedConversation = (skillId: string): CachedConversation | null => {
  if (typeof window === 'undefined') return null;
  
  try {
    const cacheKey = `chatbot_conversation_${skillId}`;
    const cached = localStorage.getItem(cacheKey);
    
    if (!cached) return null;
    
    const data: CachedConversation = JSON.parse(cached);
    
    // Check if cache is expired
    const now = Date.now();
    if (now - data.timestamp > CACHE_DURATION) {
      localStorage.removeItem(cacheKey);
      return null;
    }
    
    // Convert timestamp strings back to Date objects for messages
    data.messages = data.messages.map(msg => ({
      ...msg,
      timestamp: new Date(msg.timestamp),
    }));
    
    return data;
  } catch (error) {
    console.error('Error reading cached conversation:', error);
    return null;
  }
};

/**
 * Save conversation to localStorage
 * 
 * @param skillId - Skill identifier for the conversation
 * @param data - Conversation data to cache
 */
const saveCachedConversation = (
  skillId: string,
  messages: Message[],
  conversationHistory: Array<{ role: 'user' | 'assistant'; content: string }>,
  currentOptions: ResponseOption[]
): void => {
  if (typeof window === 'undefined') return;
  
  try {
    const cacheKey = `chatbot_conversation_${skillId}`;
    const data: CachedConversation = {
      messages,
      conversationHistory,
      currentOptions,
      timestamp: Date.now(),
    };
    
    localStorage.setItem(cacheKey, JSON.stringify(data));
  } catch (error) {
    console.error('Error saving conversation cache:', error);
  }
};

/**
 * Clear cached conversation from localStorage
 * 
 * @param skillId - Skill identifier for the conversation
 */
const clearCachedConversation = (skillId: string): void => {
  if (typeof window === 'undefined') return;
  
  try {
    const cacheKey = `chatbot_conversation_${skillId}`;
    localStorage.removeItem(cacheKey);
  } catch (error) {
    console.error('Error clearing conversation cache:', error);
  }
};

export const SkillChatbotDialog: React.FC<SkillChatbotDialogProps> = ({
  skillId,
  skillTitle,
  open,
  onOpenChange,
}) => {
  // Core state management for chatbot functionality
  const [messages, setMessages] = useState<Message[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [currentOptions, setCurrentOptions] = useState<ResponseOption[]>([]);
  const [isTyping, setIsTyping] = useState<boolean>(false);
  const [conversationHistory, setConversationHistory] = useState<Array<{
    role: 'user' | 'assistant';
    content: string;
  }>>([]);
  const [error, setError] = useState<string | null>(null);
  
  // Store timeout references for cleanup
  const [activeTimeouts, setActiveTimeouts] = useState<NodeJS.Timeout[]>([]);

  /**
   * Auto-save conversation to cache whenever state changes
   * This ensures currentOptions are always saved with the correct values
   * since React state updates are asynchronous
   */
  useEffect(() => {
    // Only save if we have messages (conversation has started)
    // Skip if we're in the middle of restoring from cache (isLoading on first render)
    if (messages.length > 0 && !isLoading) {
      saveCachedConversation(skillId, messages, conversationHistory, currentOptions);
    }
  }, [messages, conversationHistory, currentOptions, skillId]);

  /**
   * Adds a message to the conversation history
   * Cache is automatically updated by the useEffect hook above
   * 
   * @param message - The message object to append to the history
   * 
   * Validates Requirements:
   * - 7.1: Maintains conversation history state
   * - 7.2: Appends messages in chronological order
   */
  const addMessage = (message: Message) => {
    setMessages((prevMessages) => [...prevMessages, message]);
  };

  /**
   * Resets all conversation state to initial values
   * 
   * Validates Requirements:
   * - 9.3: Clears conversation history when dialog closes
   */
  const resetState = () => {
    // Clear all active timeouts to prevent memory leaks
    activeTimeouts.forEach(timeout => clearTimeout(timeout));
    setActiveTimeouts([]);
    
    setMessages([]);
    setCurrentOptions([]);
    setIsTyping(false);
    setIsLoading(false);
    setConversationHistory([]);
    setError(null);
  };

  /**
   * Clears the cached conversation for this skill
   * Useful for starting a fresh conversation
   */
  const clearConversationCache = () => {
    clearCachedConversation(skillId);
    resetState();
  };

  /**
   * Handles dialog close and cleanup logic
   * 
   * This function ensures proper cleanup of all state when the dialog
   * is closed, even if animations are in progress.
   * 
   * Validates Requirements:
   * - 9.2: Dialog closes with smooth animation
   * - 9.3: Clears conversation history when dialog closes
   */
  const handleDialogClose = () => {
    // Reset all state
    resetState();
    
    // Close dialog
    onOpenChange(false);
  };

  /**
   * Handles typewriter animation completion
   * Called when AI message finishes typing animation
   * 
   * Validates Requirements:
   * - 4.4: Response options remain hidden during typewriter effect
   * - 4.5: Response options fade in when typewriter completes
   */
  const handleTypingComplete = () => {
    setIsTyping(false);
  };

  /**
   * Fetches AI response from the chatbot API
   * 
   * @param userMessage - The user's message/question
   * @returns Promise with AI response and follow-up options
   */
  const fetchAIResponse = async (userMessage: string) => {
    try {
      const response = await chatbotApi.sendMessage({
        message: userMessage,
        skillId,
        conversationHistory,
      });

      return response;
    } catch (error) {
      console.error('Error fetching AI response:', error);
      throw error;
    }
  };

  /**
   * Loads initial AI explanation for the skill
   * Triggered when the dialog first opens
   * Checks for cached conversation first
   */
  const loadInitialResponse = async () => {
    // Check for cached conversation first
    const cached = getCachedConversation(skillId);
    
    if (cached && cached.messages.length > 0) {
      // Restore from cache - no loading or typing state needed
      setMessages(cached.messages);
      setConversationHistory(cached.conversationHistory);
      setCurrentOptions(cached.currentOptions);
      setIsLoading(false);
      setIsTyping(false); // Important: ensure options are shown immediately
      return;
    }

    // No cache found, load fresh response from API
    setIsLoading(true);
    setError(null);

    try {
      // Request initial skill explanation
      const response = await fetchAIResponse('اشرح لي هذه المهارة');

      // Add AI response to conversation history for context
      const newConversationHistory = [
        { role: 'user' as const, content: 'اشرح لي هذه المهارة' },
        { role: 'assistant' as const, content: response.response },
      ];
      setConversationHistory(newConversationHistory);

      // Add AI message to UI
      const aiMessage: Message = {
        id: generateMessageId(),
        role: 'ai',
        content: response.response,
        timestamp: new Date(),
      };

      addMessage(aiMessage);

      // Convert follow-up options to ResponseOption format
      const options = convertToResponseOptions(response.options);
      setCurrentOptions(options);
      
      // Cache is automatically saved by useEffect hook when state updates

      setIsLoading(false);
      setIsTyping(true); // Trigger typewriter effect for new responses
    } catch (error) {
      console.error('Failed to load initial response:', error);
      setError('عذراً، حدث خطأ في تحميل المحادثة. يرجى المحاولة مرة أخرى.');
      setIsLoading(false);
    }
  };

  /**
   * Handles response option selection
   * 
   * This function implements the core interaction logic when a student
   * clicks on a response option button.
   * 
   * @param option - The selected response option object
   * 
   * Validates Requirements:
   * - 5.3: Selected option text added as student message to history
   * - 5.4: Loading state displays before next AI response
   * 
   * Flow:
   * 1. Add student's selected option as a message
   * 2. Show loading state
   * 3. Send message to AI with conversation context
   * 4. Display AI response with new follow-up options
   * 5. Update cache with new conversation state
   */
  const handleResponseSelect = async (option: ResponseOption) => {
    // Add selected option text as student message to history
    const studentMessage: Message = {
      id: generateMessageId(),
      role: 'student',
      content: option.text,
      timestamp: new Date(),
    };
    addMessage(studentMessage);

    // Update conversation history for API context
    const updatedHistory = [
      ...conversationHistory,
      { role: 'user' as const, content: option.text },
    ];
    setConversationHistory(updatedHistory);

    // Clear current options and show loading state
    setCurrentOptions([]);
    setIsLoading(true);
    setError(null);

    try {
      // Fetch AI response with full conversation context
      const response = await chatbotApi.sendMessage({
        message: option.text,
        skillId,
        conversationHistory: updatedHistory,
      });

      // Add AI response to conversation history
      const newHistory = [
        ...updatedHistory,
        { role: 'assistant' as const, content: response.response },
      ];
      setConversationHistory(newHistory);

      // Add AI message to UI
      const aiMessage: Message = {
        id: generateMessageId(),
        role: 'ai',
        content: response.response,
        timestamp: new Date(),
      };
      addMessage(aiMessage);

      // Convert follow-up options to ResponseOption format
      const options = convertToResponseOptions(response.options);
      setCurrentOptions(options);
      
      // Cache is automatically saved by useEffect hook when state updates

      setIsLoading(false);
      setIsTyping(true); // Trigger typewriter effect
    } catch (error) {
      console.error('Failed to get AI response:', error);
      setError('عذراً، حدث خطأ في الحصول على الرد. يرجى المحاولة مرة أخرى.');
      setIsLoading(false);
      
      // Restore options so user can try again
      setCurrentOptions([option]);
    }
  };

  // Reset state when dialog closes
  // Ensures cleanup happens when dialog is closed mid-animation
  useEffect(() => {
    if (!open) {
      // Small delay to allow dialog close animation to start
      // before resetting state (prevents visual glitches)
      const cleanupTimer = setTimeout(() => {
        resetState();
      }, 50);
      
      // Cleanup function to clear timeout if component unmounts
      return () => clearTimeout(cleanupTimer);
    }
  }, [open]);

  // Load initial AI response when dialog opens
  // Validates Requirements: 1.4, 2.1, 2.3, 2.4, 3.1
  useEffect(() => {
    if (open && messages.length === 0) {
      // Load initial skill explanation from AI
      loadInitialResponse();
    }
  }, [open]);

  return (
    <Dialog open={open} onOpenChange={handleDialogClose}>
      <DialogContent
        className="h-full !fixed !left-[50%] !top-[50%] !translate-x-[-50%] !translate-y-[-50%] 
                   w-full sm:w-[90%] md:w-[85%] lg:w-[75%] xl:w-[65%] sm:max-w-[900px]
                   max-h-[95vh] sm:max-h-[90vh]
                   flex flex-col p-0 font-cairo text-base border-2 border-primary/20
                   shadow-xl animate-in fade-in-0 zoom-in-95 duration-200 overflow-hidden"
        dir="rtl"
        style={{
          fontFeatureSettings: '"liga" 1, "calt" 1',
          textRendering: 'optimizeLegibility',
          WebkitFontSmoothing: 'antialiased',
          MozOsxFontSmoothing: 'grayscale',
          // Subtle animated glow effect on border - Task 20.2
          boxShadow: '0 0 0 1px hsl(var(--primary) / 0.1), 0 0 20px -5px hsl(var(--primary) / 0.15)',
          animation: 'subtle-border-pulse 3s ease-in-out infinite',
        }}
      >
        <DialogHeader className="p-4 sm:p-6 pb-3 sm:pb-4 border-b border-border/50 bg-gradient-to-b from-accent/5 to-transparent">
          <div className="flex items-center justify-between gap-2">
            <DialogTitle 
              className="text-lg sm:text-xl font-bold text-right leading-relaxed flex-1 line-clamp-2"
              style={{
                fontFeatureSettings: '"liga" 1, "calt" 1',
                textRendering: 'optimizeLegibility',
                WebkitFontSmoothing: 'antialiased',
                MozOsxFontSmoothing: 'grayscale',
                lineHeight: '1.75',
              }}
            >
              {skillTitle}
            </DialogTitle>
            {messages.length > 0 && (
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  clearConversationCache();
                  loadInitialResponse();
                }}
                className="mr-2 px-2 sm:px-3 py-1 sm:py-1.5 text-xs rounded-md bg-accent/50 hover:bg-accent text-accent-foreground transition-colors whitespace-nowrap"
                title="بدء محادثة جديدة"
              >
                <span className="hidden sm:inline">محادثة جديدة</span>
                <span className="sm:hidden">جديد</span>
              </button>
            )}
          </div>
        </DialogHeader>

        <div className="flex-1 overflow-hidden">
          {/* Display error message if API call fails */}
          {error && (
            <div className="p-4 sm:p-6">
              <div className="bg-destructive/10 border border-destructive/20 rounded-lg p-3 sm:p-4 text-destructive text-center text-sm sm:text-base">
                {error}
              </div>
            </div>
          )}

          {/* Display LoadingState while loading initial message */}
          {isLoading && messages.length === 0 && !error ? (
            <div className="p-4 sm:p-6 animate-in fade-in duration-200">
              <LoadingState />
            </div>
          ) : (
            <div className="h-full flex flex-col animate-in fade-in duration-200">
              {/* Conversation History */}
              <ConversationHistory 
                messages={messages} 
                isTyping={isTyping}
                onTypingComplete={handleTypingComplete}
              />

              {/* Loading state during response transitions */}
              {isLoading && messages.length > 0 && (
                <div className="px-4 sm:px-6 py-3 sm:py-4 animate-in fade-in duration-200">
                  <LoadingState variant="skeleton" />
                </div>
              )}

              {/* Response Options */}
              {!isLoading && !isTyping && currentOptions.length > 0 && !error && (
                <div className="px-4 sm:px-6 pb-4 sm:pb-6">
                  <ResponseOptions
                    options={currentOptions}
                    onSelect={handleResponseSelect}
                    disabled={isLoading || isTyping}
                  />
                </div>
              )}
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
};
